export const Mockup: Array<String> = [
  "/mockup1.png",
  "/mockup2.png",
  "/mockup3.png",
  "/mockup4.png",
  "/mockup1.png",
  "/mockup2.png",
  "/mockup3.png",
  "/mockup4.png",
  "/mockup1.png",
  "/mockup2.png",
  "/mockup3.png",
  "/mockup4.png",
  "/mockup1.png",
  "/mockup2.png",
  "/mockup3.png",
  "/mockup4.png",
];
