export const Mockup: Array<String> = [
  "/images/mockup1.png",
  "/images/mockup2.png",
  "/images/mockup3.png",
  "/images/mockup4.png",
  "/images/mockup1.png",
  "/images/mockup2.png",
  "/images/mockup3.png",
  "/images/mockup4.png",
  "/images/mockup1.png",
  "/images/mockup2.png",
  "/images/mockup3.png",
  "/images/mockup4.png",
  "/images/mockup1.png",
  "/images/mockup2.png",
  "/images/mockup3.png",
  "/images/mockup4.png",
];
