/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/pTPeCQWzftC
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"

export function ArticleDetailSection() {
  return (
    <div className="max-w-6xl mx-auto py-12 md:py-16 lg:py-20 px-4 md:px-6">
      <div className="mb-8 md:mb-10 lg:mb-12">
        <h2 className="text-3xl font-bold tracking-tight sm:text-4xl md:text-5xl">
          Unlocking the Power of React: A Beginner's Guide
        </h2>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 lg:gap-12">
        <div>
          <img
            alt="Article Cover"
            className="w-full h-auto rounded-lg object-cover"
            height={500}
            src="/placeholder.svg"
            style={{
              aspectRatio: "800/500",
              objectFit: "cover",
            }}
            width={800}
          />
        </div>
        <div>
          <div className="mb-4 text-sm text-gray-500 dark:text-gray-400">June 1, 2023</div>
          <div className="mb-6">
            <p className="text-gray-500 dark:text-gray-400 leading-relaxed">
              Dive into the world of React and learn how to build dynamic and responsive web applications. This
              comprehensive guide covers the fundamentals of React, from setting up your development environment to
              creating complex user interfaces.
            </p>
          </div>
          <div className="mb-6">
            <h3 className="text-2xl font-bold mb-4">Table of Contents</h3>
            <ul className="space-y-2 text-gray-500 dark:text-gray-400">
              <li>
                <Link className="hover:text-primary transition-colors" href="#">
                  Introduction to React
                </Link>
              </li>
              <li>
                <Link className="hover:text-primary transition-colors" href="#">
                  Setting up Your Development Environment
                </Link>
              </li>
              <li>
                <Link className="hover:text-primary transition-colors" href="#">
                  Building Your First React Component
                </Link>
              </li>
              <li>
                <Link className="hover:text-primary transition-colors" href="#">
                  State Management in React
                </Link>
              </li>
              <li>
                <Link className="hover:text-primary transition-colors" href="#">
                  Routing and Navigation
                </Link>
              </li>
              <li>
                <Link className="hover:text-primary transition-colors" href="#">
                  Styling and Theming
                </Link>
              </li>
              <li>
                <Link className="hover:text-primary transition-colors" href="#">
                  Fetching and Handling Data
                </Link>
              </li>
              <li>
                <Link className="hover:text-primary transition-colors" href="#">
                  Deploying Your React Application
                </Link>
              </li>
            </ul>
          </div>
          <div className="mb-6">
            <h3 className="text-2xl font-bold mb-4">About the Author</h3>
            <div className="flex items-center space-x-4">
              <Avatar className="w-12 h-12 border">
                <AvatarImage alt="@johndoe" src="/placeholder-user.jpg" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
              <div>
                <div className="font-medium">John Doe</div>
                <div className="text-sm text-gray-500 dark:text-gray-400">Front-end Developer</div>
              </div>
            </div>
          </div>
          <div className="flex items-center space-x-4">
            <Button>Read More</Button>
            <Button variant="outline">Share</Button>
          </div>
        </div>
      </div>
    </div>
  )
}
