/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/A6YMV3aGdnN
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function ArticleSection() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center justify-center space-y-4 text-center">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              Latest Articles
            </h2>
            <p className="max-w-[700px] text-gray-500 dark:text-gray-400 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              Discover our latest insights and stories.
            </p>
          </div>
        </div>
        <div className="mx-auto grid gap-8 py-12 sm:grid-cols-2 lg:grid-cols-3">
          <div className="group relative overflow-hidden rounded-lg shadow-lg transition-transform duration-300 ease-in-out hover:-translate-y-2 hover:shadow-xl">
            <a className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View article</span>
            </a>
            <img
              alt="Article 1"
              className="h-60 w-full object-cover"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "450/300",
                objectFit: "cover",
              }}
              width={450}
            />
            <div className="bg-white p-4 dark:bg-gray-950">
              <h3 className="text-lg font-semibold md:text-xl">
                Unlocking the Power of Automation
              </h3>
              <p className="line-clamp-2 text-sm text-gray-500 dark:text-gray-400">
                Discover how automation can streamline your workflows and boost
                productivity.
              </p>
            </div>
          </div>
          <div className="group relative overflow-hidden rounded-lg shadow-lg transition-transform duration-300 ease-in-out hover:-translate-y-2 hover:shadow-xl">
            <a className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View article</span>
            </a>
            <img
              alt="Article 2"
              className="h-60 w-full object-cover"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "450/300",
                objectFit: "cover",
              }}
              width={450}
            />
            <div className="bg-white p-4 dark:bg-gray-950">
              <h3 className="text-lg font-semibold md:text-xl">
                Mastering the Art of Responsive Design
              </h3>
              <p className="line-clamp-2 text-sm text-gray-500 dark:text-gray-400">
                Learn how to create websites that adapt seamlessly to any
                device.
              </p>
            </div>
          </div>
          <div className="group relative overflow-hidden rounded-lg shadow-lg transition-transform duration-300 ease-in-out hover:-translate-y-2 hover:shadow-xl">
            <a className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View article</span>
            </a>
            <img
              alt="Article 3"
              className="h-60 w-full object-cover"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "450/300",
                objectFit: "cover",
              }}
              width={450}
            />
            <div className="bg-white p-4 dark:bg-gray-950">
              <h3 className="text-lg font-semibold md:text-xl">
                Unleashing the Potential of Data Analytics
              </h3>
              <p className="line-clamp-2 text-sm text-gray-500 dark:text-gray-400">
                Discover how data-driven insights can transform your business.
              </p>
            </div>
          </div>
          <div className="group relative overflow-hidden rounded-lg shadow-lg transition-transform duration-300 ease-in-out hover:-translate-y-2 hover:shadow-xl">
            <a className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View article</span>
            </a>
            <img
              alt="Article 4"
              className="h-60 w-full object-cover"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "450/300",
                objectFit: "cover",
              }}
              width={450}
            />
            <div className="bg-white p-4 dark:bg-gray-950">
              <h3 className="text-lg font-semibold md:text-xl">
                Navigating the Future of Web Development
              </h3>
              <p className="line-clamp-2 text-sm text-gray-500 dark:text-gray-400">
                Explore the latest trends and technologies shaping the web
                development landscape.
              </p>
            </div>
          </div>
          <div className="group relative overflow-hidden rounded-lg shadow-lg transition-transform duration-300 ease-in-out hover:-translate-y-2 hover:shadow-xl">
            <a className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View article</span>
            </a>
            <img
              alt="Article 5"
              className="h-60 w-full object-cover"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "450/300",
                objectFit: "cover",
              }}
              width={450}
            />
            <div className="bg-white p-4 dark:bg-gray-950">
              <h3 className="text-lg font-semibold md:text-xl">
                Optimizing Your Content Strategy
              </h3>
              <p className="line-clamp-2 text-sm text-gray-500 dark:text-gray-400">
                Learn how to create engaging and effective content that
                resonates with your audience.
              </p>
            </div>
          </div>
          <div className="group relative overflow-hidden rounded-lg shadow-lg transition-transform duration-300 ease-in-out hover:-translate-y-2 hover:shadow-xl">
            <a className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View article</span>
            </a>
            <img
              alt="Article 6"
              className="h-60 w-full object-cover"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "450/300",
                objectFit: "cover",
              }}
              width={450}
            />
            <div className="bg-white p-4 dark:bg-gray-950">
              <h3 className="text-lg font-semibold md:text-xl">
                Embracing the Future of Collaboration
              </h3>
              <p className="line-clamp-2 text-sm text-gray-500 dark:text-gray-400">
                Discover how to foster effective collaboration in a distributed
                work environment.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
