import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import Providers from "./providers";
import { Toaster } from "@/components/ui/toaster";

export const metadata = {
  title: "SINGA Article",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable}`}
      suppressHydrationWarning
    >
      <body>
        <Providers>
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
