import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import React from "react";

export const metadata = {
  title: "Dashboard | Singa Article",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function DashboardPage() {
  return (
    <Card className="">
      <CardHeader>
        <CardTitle>User Details</CardTitle>
        <CardDescription>
          Used to identify your store in the marketplace.
        </CardDescription>
      </CardHeader>
      <CardContent></CardContent>
    </Card>
  );
}
