import MainLayout from "@/layout/MainLayout";
import { getUser } from "../auth";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Dashboard | Singa Article",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getUser();
  if (!user) {
    redirect("/login");
  }

  return <MainLayout>{children}</MainLayout>;
}
